[features]
seeds = false
skip-lint = false
[programs.devnet]
armory_staking = "GqVfxjhCXWvhQtMg9x2K2BqhRDdC35MXxDjbLVdhaDv2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/fury/ubuntu-deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
